plugin_repo(
    name = "go",
    revision = "v1.7.6",
    plugin = "go-rules",
    owner = "please-build",
)

plugin_repo(
    name = "shell",
    revision = "v0.2.0",
    plugin = "shell-rules",
    owner = "please-build",
)

plugin_repo(
  name = "docker",
  revision = "v0.1.0",
  plugin = "docker-rules",
  owner = "please-build",
)
plugin_repo(
  name = "k8s",
  revision = "v0.1.0",
  plugin = "k8s-rules",
  owner = "please-build",
)
